version: "3.5"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
#      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adacta-cms
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
  php-fpm:
    image: webdevops/php-dev:7.4
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - mysql
  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "81:80"
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm
